### ISSUE TITLE
ERROR TS6054: File '~lib/@graphprotocol/graph-ts.ts' not found.

### ISSUE THREAD

**Issue by 0xbe1** [as-pect/as-pect#388]
@willemneal @jtenner hi, i am experiencing a similar issue as @zimmah does in #364 .

The code can be found here: https://github.com/0xbe1/graph-ts-playground/pull/2

basically, in my example.spec.ts, I try to import the @graphprotocol/graph-ts library, however it shows error:

```
$ yarn test
yarn run v1.22.17
warning package.json: No license field
$ asp --verbose
       ___   _____                       __
      /   | / ___/      ____  ___  _____/ /_
     / /| | \__ \______/ __ \/ _ \/ ___/ __/
    / ___ |___/ /_____/ /_/ /  __/ /__/ /_
   /_/  |_/____/     / .___/\___/\___/\__/
                    /_/

⚡AS-pect⚡ Test suite runner [6.2.4]

[Log] Loading asc compiler
Assemblyscript Folder:assemblyscript
[Log] Compiler loaded in 308.139ms.
[Log] Using configuration /Users/yiksanchan/source/0xbe1/web3/graph-ts-playground/as-pect.config.js
[Log] Using VerboseReporter
[Log] Including files: assembly/__tests__/**/*.spec.ts
[Log] Running tests that match: (:?)
[Log] Running groups that match: (:?)
[Log] Effective command line args:
  [TestFile.ts] node_modules/@as-pect/assembly/assembly/index.ts --runtime incremental --debug --binaryFile output.wasm --explicitStart --use ASC_RTRACE=1 --exportTable --importMemory --transform /Users/yiksanchan/source/0xbe1/web3/graph-ts-playground/node_modules/@as-pect/core/lib/transform/index.js

ERROR TS6054: File '~lib/@graphprotocol/graph-ts.ts' not found.

 import {BigInt} from "@graphprotocol/graph-ts"
                      ~~~~~~~~~~~~~~~~~~~~~~~~~
 in assembly/__tests__/example.spec.ts(1,22)

[Error] There was a compilation error when trying to create the wasm binary for file: assembly/__tests__/example.spec.ts.
[1 parse error(s)]
error Command failed with exit code 1.
```

Any help? Thank you!

**Comment by 0xbe1** [comment]
> Looking into it, they didn't follow the convention of placing their main file in `assembly/index.ts`, nor did they add `"ascMain": "index.ts"` to their `package.json`.
> 
> I tried adding `ascMain` and it fixed it. So either try forking their repo, adding that, and then depending on their github repo. Or make a PR to their repo.
> 
> The newest version `0.20.*` of AS removes `ascMain`. But as of now as-pect doesn't support the newest version.

Thank you so much!!! I wonder when will as-pect support 0.20.* if that's the plan? At the same time I will PR on their repo.

**Comment by willemneal** [comment]
I need to add a note to the README but this project is currently in maintenance mode, with no plans for future development.  Though I would gladly help transition to anyone that would like to work on it.

**Comment by roaminroe** [comment]
Hi, @willemneal ! would you be able to tell us what would need to be updated to make this package work with AS 0.20.*? That'd be too bad if this project were to die :(
